### ISSUE TITLE
apply-filters default value is wrong

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ts/checkmarx-cxflow-orb#8]
**Orb Version**
Latest

**Describe the bug**
The default for `apply-filters`:

```
  apply-filters:
    type: string
    default: "--filter-severity=High --filter-severity=Medium --filter-severity=Low"
    description: "Select report filter criteria"
```
The option `--filter-severity` does not exist, so a default config yaml file in the jar defaults the filter to High.  A customer was scanning a project that had 0 highs and trying to push results to Jira, so no results would be created in Jira causing confusion.

We used this workaround in the config.yml:

`apply-filters: '--cx-flow.filter-severity=High,Medium,Low,Informational'`

**To Reproduce**

Scan a project with 0 high results, note the are no reported results if trying to update Jira.

**Expected behavior**
High, Medium, Low results appear in the issue tracker by default.
